import { Router } from "express";
import authRoutes from "./autentficacao/auth.routes";
import funcionarioRoutes from "./funcionario/funcionario.routes";
import restauranteRoutes from "./restaurante/restaurante.routes";
import restauranteProtectedRoutes from "./restaurante/restaurante.protected.routes";
import rolesRoutes from "./roles/roles.routes";
import pedidoRoutes from "./pedido/pedido.routes";
import produtoRoutes from "./produto/produto.routes";
import comboRoutes     from "./combo/combo.routes";
import promocaoRoutes  from "./promocao/promocao.routes";
import gastoRoutes from "./gasto/gasto.routes";
import financeiroRoutes from "./financeiro/financeiro.routes";
import ingredienteRoutes from "./ingrediente/ingrediente.routes";
import cardapioRoutes from "./cardapio/cardapio.routes";

export const publicRoutes = Router();
publicRoutes.use("/auth", authRoutes);
publicRoutes.use("/roles", rolesRoutes);
publicRoutes.use("/restaurantes", restauranteRoutes);

export const protectedRoutes = Router();
protectedRoutes.use("/restaurantes",       restauranteProtectedRoutes);
protectedRoutes.use("/funcionarios",       funcionarioRoutes);
protectedRoutes.use("/produtos",           produtoRoutes);
protectedRoutes.use("/combos",             comboRoutes);
protectedRoutes.use("/promocoes",          promocaoRoutes);
protectedRoutes.use("/pedidos",            pedidoRoutes);
protectedRoutes.use("/gastos",             gastoRoutes);
protectedRoutes.use("/financeiro",         financeiroRoutes);
protectedRoutes.use("/ingredientes",       ingredienteRoutes);
protectedRoutes.use("/cardapio",           cardapioRoutes);
